apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-api-weather-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JFKTBonny/Gitops_Weather_App.git   # #<-- change this
    targetRevision: main
    path: deployment                                               # <-- adjust if manifests are in a folder
  destination:
    server: https://kubernetes.default.svc
    namespace: weather-app-for-real
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true