apiVersion: v1
kind: Secret
metadata:
  name: weather-api-key
  namespace: weather-app-for-real
type: Opaque
data:
  WEATHER_API_KEY: MjVmMDM0YjNiZGI1NGU0Nzg1MzE5MjQ1MDI1MjgwOA==


# apiVersion: v1
# kind: Secret
# metadata:
#   name: weather-api-key
#   namespace: weather-app-for-real
# type: Opaque
# stringData:
#   WEATHER_API_KEY: 25f034b3bdb54e47853192450252808

